---
- name: Clear hostname file
  become: true
  lineinfile:
    path: /etc/hostname
    state: absent
    # match all lines
    regexp: "^.*$"

- name: Set hostname
  become: true
  lineinfile:
    path: /etc/hostname
    line: "{{ static_hostname }}"
    create: true

- name: Update hosts file
  become: true
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1   {{ static_hostname }}"
    create: true
    regexp: '^127\.0\.0\.1\s+localhost$'

- name: Reboot system
  become: true
  reboot:
